#!/bin/bash
# ============================================================================
# Zigbee2MQTT Installation Script for Wall Clock Home Hub
# Sets up Mosquitto MQTT broker and Zigbee2MQTT
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
ZIGBEE_DEVICE="/dev/ttyUSB0"
Z2M_DIR="/opt/zigbee2mqtt"
Z2M_DATA="/opt/zigbee2mqtt/data"
USER="admin"

echo -e "${CYAN}============================================${NC}"
echo -e "${CYAN}  Zigbee2MQTT Setup for Home Hub${NC}"
echo -e "${CYAN}============================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run with sudo: sudo ./setup-zigbee2mqtt.sh${NC}"
    exit 1
fi

# ============================================================================
# Check for Zigbee adapter
# ============================================================================

echo -e "${CYAN}[1/6]${NC} Checking for Zigbee adapter..."

if [ ! -e "$ZIGBEE_DEVICE" ]; then
    echo -e "${RED}  [ERROR]${NC} Zigbee adapter not found at $ZIGBEE_DEVICE"
    echo -e "${YELLOW}  Please check that your Zigbee USB dongle is connected${NC}"
    
    # Try to find any serial devices
    echo -e "${YELLOW}  Available serial devices:${NC}"
    ls -la /dev/ttyUSB* /dev/ttyACM* 2>/dev/null || echo "  None found"
    exit 1
fi

echo -e "${GREEN}  [OK]${NC} Found Zigbee adapter at $ZIGBEE_DEVICE"

# Check adapter details
ADAPTER_INFO=$(udevadm info -a -n $ZIGBEE_DEVICE 2>/dev/null | grep -m1 'ATTRS{product}' | sed 's/.*=="\(.*\)"/\1/' || echo "Unknown")
echo -e "${YELLOW}  Adapter: ${ADAPTER_INFO}${NC}"
echo ""

# ============================================================================
# Install Mosquitto MQTT Broker
# ============================================================================

echo -e "${CYAN}[2/6]${NC} Installing Mosquitto MQTT broker..."

apt-get update -qq > /dev/null 2>&1
apt-get install -y mosquitto mosquitto-clients > /dev/null 2>&1

# Configure Mosquitto for local connections
cat > /etc/mosquitto/conf.d/wallclock.conf << 'EOF'
# Wall Clock Home Hub Mosquitto Configuration
listener 1883 localhost
allow_anonymous true

# WebSocket listener (optional, for web clients)
# listener 9001
# protocol websockets
EOF

# Restart Mosquitto
systemctl enable mosquitto > /dev/null 2>&1
systemctl restart mosquitto

if systemctl is-active --quiet mosquitto; then
    echo -e "${GREEN}  [OK]${NC} Mosquitto installed and running"
else
    echo -e "${RED}  [ERROR]${NC} Mosquitto failed to start"
    exit 1
fi
echo ""

# ============================================================================
# Install Node.js (required for Zigbee2MQTT)
# ============================================================================

echo -e "${CYAN}[3/6]${NC} Checking Node.js..."

if ! command -v node &> /dev/null; then
    echo -e "${YELLOW}  Installing Node.js...${NC}"
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - > /dev/null 2>&1
    apt-get install -y nodejs > /dev/null 2>&1
fi

NODE_VERSION=$(node --version)
echo -e "${GREEN}  [OK]${NC} Node.js ${NODE_VERSION} available"
echo ""

# ============================================================================
# Install Zigbee2MQTT
# ============================================================================

echo -e "${CYAN}[4/6]${NC} Installing Zigbee2MQTT..."

if [ ! -d "$Z2M_DIR" ]; then
    echo -e "${YELLOW}  Cloning Zigbee2MQTT...${NC}"
    git clone --depth 1 https://github.com/Koenkk/zigbee2mqtt.git $Z2M_DIR > /dev/null 2>&1
fi

cd $Z2M_DIR
echo -e "${YELLOW}  Installing dependencies (this may take a few minutes)...${NC}"
npm ci --production > /dev/null 2>&1

echo -e "${GREEN}  [OK]${NC} Zigbee2MQTT installed"
echo ""

# ============================================================================
# Configure Zigbee2MQTT
# ============================================================================

echo -e "${CYAN}[5/6]${NC} Configuring Zigbee2MQTT..."

mkdir -p $Z2M_DATA

# Create configuration file
cat > $Z2M_DATA/configuration.yaml << EOF
# Zigbee2MQTT configuration for Wall Clock Home Hub
# Generated by setup script

homeassistant: false

permit_join: false

mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883

serial:
  port: $ZIGBEE_DEVICE
  # Adapter type will be auto-detected
  # adapter: zstack  # Uncomment if auto-detect fails

frontend:
  port: 8080
  host: 0.0.0.0

advanced:
  log_level: info
  log_output:
    - console
  network_key: GENERATE
  pan_id: GENERATE
  channel: 11
  
  # Enable touchlink for IKEA/Philips devices
  # touchlink: true

# Device-specific settings can be added here
devices: {}

# Group settings
groups: {}
EOF

# Set permissions
chown -R $USER:$USER $Z2M_DIR

echo -e "${GREEN}  [OK]${NC} Zigbee2MQTT configured"
echo ""

# ============================================================================
# Create Systemd Service
# ============================================================================

echo -e "${CYAN}[6/6]${NC} Creating systemd service..."

cat > /etc/systemd/system/zigbee2mqtt.service << EOF
[Unit]
Description=Zigbee2MQTT
After=network.target mosquitto.service
Requires=mosquitto.service

[Service]
Type=simple
User=$USER
WorkingDirectory=$Z2M_DIR
ExecStart=/usr/bin/node $Z2M_DIR/index.js
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable zigbee2mqtt > /dev/null 2>&1
systemctl start zigbee2mqtt

# Wait for startup
echo -e "${YELLOW}  Waiting for Zigbee2MQTT to start...${NC}"
sleep 10

if systemctl is-active --quiet zigbee2mqtt; then
    echo -e "${GREEN}  [OK]${NC} Zigbee2MQTT service running"
else
    echo -e "${YELLOW}  [WARNING]${NC} Service may still be starting..."
    echo -e "${YELLOW}  Check logs: sudo journalctl -u zigbee2mqtt -f${NC}"
fi
echo ""

# ============================================================================
# Install paho-mqtt for Python
# ============================================================================

echo -e "${CYAN}[BONUS]${NC} Installing Python MQTT library..."

if [ -f "/home/admin/wallclock/venv/bin/pip" ]; then
    /home/admin/wallclock/venv/bin/pip install paho-mqtt > /dev/null 2>&1
    echo -e "${GREEN}  [OK]${NC} paho-mqtt installed in wallclock venv"
fi
echo ""

# ============================================================================
# Summary
# ============================================================================

echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  Installation Complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "${CYAN}Services Status:${NC}"
echo -e "  Mosquitto:    $(systemctl is-active mosquitto)"
echo -e "  Zigbee2MQTT:  $(systemctl is-active zigbee2mqtt)"
echo ""
echo -e "${CYAN}Access Points:${NC}"
echo -e "  ${YELLOW}•${NC} Home Hub:        http://localhost:8000/homehub"
echo -e "  ${YELLOW}•${NC} Z2M Frontend:    http://localhost:8080"
echo -e "  ${YELLOW}•${NC} MQTT Broker:     localhost:1883"
echo ""
echo -e "${CYAN}Useful Commands:${NC}"
echo -e "  ${YELLOW}•${NC} Z2M logs:        ${GREEN}sudo journalctl -u zigbee2mqtt -f${NC}"
echo -e "  ${YELLOW}•${NC} Restart Z2M:     ${GREEN}sudo systemctl restart zigbee2mqtt${NC}"
echo -e "  ${YELLOW}•${NC} Z2M status:      ${GREEN}systemctl status zigbee2mqtt${NC}"
echo -e "  ${YELLOW}•${NC} MQTT test:       ${GREEN}mosquitto_sub -t 'zigbee2mqtt/#' -v${NC}"
echo ""
echo -e "${CYAN}Configuration:${NC}"
echo -e "  ${YELLOW}•${NC} Z2M config:      $Z2M_DATA/configuration.yaml"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo -e "  ${YELLOW}1.${NC} Restart the wallclock service:"
echo -e "     ${GREEN}sudo systemctl restart wallclock${NC}"
echo ""
echo -e "  ${YELLOW}2.${NC} Open Home Hub in your browser:"
echo -e "     ${GREEN}http://$(hostname -I | awk '{print $1}'):8000/homehub${NC}"
echo ""
echo -e "  ${YELLOW}3.${NC} Add your first device by clicking 'Add Device'"
echo ""
echo -e "${GREEN}============================================${NC}"
